### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by irsanvanwel** [artemeff/jwt#11]
For some reason I get error:
{undef,
    [{jsx,encode,

With version 0.1.4, when I reverted back to 0.1.3 everything works normal.
This is on Windows 10 x64.

Perhaps it is an issue with the used jsx version?

**Comment by irsanvanwel** [comment]
Okay so seems I found the issue if I add specifically the latest version of jsx to my own rebar.conf it start to work.
I added {jsx, "2.9.0"} to my conf.
Maybe stating a specific version in the rebar.conf of this project will fix this issue ?

**Comment by artemeff** [comment]
Oh, i'm sorry, my rebar3_hex plugin was outdated
0.1.4 retired now on hex.pm, please upgrade to 0.1.5

**Comment by irsanvanwel** [comment]
Thanks for the swift reply and fix!
