### ISSUE TITLE
hex package is broken

### ISSUE THREAD

**Issue by fogfish** [artemeff/jwt#12]
I am not sure if hex package is broken... but my library fails if I am taking `jwt` from hex.

e.g. I do have 
```
{deps, [
   jwt, ...
```
then rebar3 do not resolves `jsx` and `base64url` deps. My tests are failed:

```
=== Reason: {no_app,jsx}
...
=== Reason: undefined function base64url:encode/1
```
 
All tests are passed if I am fetching deps from GitHub.
```
{deps, [
   {jwt, ".*",
      {git, "https://github.com/artemeff/jwt", {branch, master}}
   }, ...
```

**Comment by artemeff** [comment]
@fogfish check that you don't use retired version https://hex.pm/packages/jwt/0.1.4, it doesn't have any dependencies :)

**Comment by fogfish** [comment]
Indeed! Thank you for hint!
