### ISSUE TITLE
hex.pm package version is broken

### ISSUE THREAD

**Issue by fogfish** [artemeff/jwt#35]
`rebar.config` uses upstream hex version `0.1.8`.
It fails on `jwt:decode` at `maps:get(<<"iss">>, ...`

due to double encoding, see source code
```
encode(Alg, ClaimsSet, Expiration, Key) ->
    %% Note: here you do double encoding of claims
    Claims = base64url:encode(jsx:encode(jwt_add_exp(ClaimsSet, Expiration))),
    encode(Alg, Claims, Key).
``` 

however, `master` of this repo do not have this issue. 

Could you please update hex package?

**Comment by artemeff** [comment]
https://hex.pm/packages/jwt/0.1.9
